### ISSUE TITLE
Stop appending `.gz` to BAM outputs

### ISSUE THREAD

**Issue by fanninpm** [usafsam/mad_river_wf#16]
This has something to do with GenBank (?) submissions. @friesac can explain more by commenting below or by editing this comment.

**Comment by friesac** [comment]
Thanks for starting this one @fanninpm. Right, we can't upload .bam.gz files to Genbank without first changing back to .bam, overall just annoying. While first and foremost we need to be conscious of space concerns these bam files aren't really that large compared to the compressed output. The only reason we had originally compressed the .bam was that they were an artifact of the first bbtools pipeline suggestions from Brian Bushnell. I think this should simply be a case of removing the .gz extension on .bam outputs in the samtools.nf module.
