### ISSUE TITLE
Add new primers to Midnight set

### ISSUE THREAD

**Issue by fanninpm** [usafsam/mad_river_wf#20]
These are primers to be used **in addition to** our current suite (it's helpful to think of these collectively as a "Midnight v1.2 primer set"). This will throw a slight wrench in my plans with #14, as there's no standardized way to specify a sequence in a BED file. (Perhaps we could take a look at using a modified ARTIC-style TSV file, with every possible data point we may need, as a single source of truth.)

# New Primers
The following primer is part of the "Midnight v1.1" primer set:
- \>SARSCoV_1200_28_LEFT_OMICRON (C27807T)
  TTTGTGCTTTTTAGCCTTTCTG**T**T

In addition to the previous primer, the following three primers are part of the "Midnight v1.2" primer set:
- \>SARSCoV_1200_22_RIGHT_OMICRON (G22599A)
  AACAGATGCAAAT**T**TGGTGGCG
- \>SARSCoV_1200_23_LEFT_OMICRON (C22522T)
  ACTTTAGAGT**T**CAACCAACAGAATCT
- \>SARSCoV_1200_26_LEFT_OMICRON (C25708T)
  GCCTTGAAGCCCCTTTT**T**TCTA

# References

- https://twitter.com/freed_nikki/status/1464477513107730433?s=20
- https://twitter.com/DrT1973/status/1483924384238628866?s=20

**Comment by fanninpm** [comment]
Possible inspiration for that single-source-of-truth TSV file (this has a few unnecessary columns, such as melting temperature and GC content):

https://github.com/stefanusbernard/Nanopore-SARS-CoV-2-Amplicon-Drop-Analysis/blob/main/midnight_ncov.csv

**Comment by fanninpm** [comment]
In addition to the previous primers, we're thinking of adding the 71_RIGHT primer from ARTIC v4.1:

- >SARSCoV_1200_21_RIGHT_OMICRON (EXTENDED)  
TGAGGATCTGAAAACTTTGTCAGGG

This has different coordinates: 21700 5' -> 3' 21675 on the negative strand.

Reference:
- https://github.com/artic-network/artic-ncov2019/blob/master/primer_schemes/nCoV-2019/V4.1/SARS-CoV-2.primer.bed

**Comment by fanninpm** [comment]
Here is a summary of the primers being included:

| Primer Name                                                | v1.0 | v1.1 | v1.2 | v2.0 |
|------------------------------------------------------------|------|------|------|------|
| 28_Left_Omicron (C27807T)                                  | ❌    | ✅    | ✅    | ✅    |
| 22_Right_Omicron (G22599A)                                 | ❌    | ❌    | ✅    | ✅    |
| 23_Left_Omicron (C22522T)                                  | ❌    | ❌    | ✅    | ✅    |
| 26_Left_Omicron (C25708T)                                  | ❌    | ❌    | ✅    | ✅    |
| 21_Right_Omicron (extended, same as ARTIC v4.1's 71_Right) | ❌    | ❌    | ❌    | ✅    |

**Comment by friesac** [comment]
Just to clarify, we're not using the extended 21R like Oxford Nanopore Epi2me. Instead IDT has actually included ARTIC 71_Right.

**Comment by fanninpm** [comment]
This is correct. ARTIC 71_Right is completely different from Midnight 21_Right. Oxford Nanopore's BED file has a slightly longer range for the primer, so that's where I got the "extended" part from.
