### ISSUE TITLE
Feed combined consensus FASTA to pangolin and nextclade

### ISSUE THREAD

**Issue by fanninpm** [usafsam/mad_river_wf#5]
Currently, we are feeding individual FASTA files into pangolin and nextclade processes. It would be more efficient for these processes to receive the combined consensus FASTA file as input. Erin Young did something similar with the Cecret pipeline:

https://github.com/UPHL-BioNGS/Cecret/blob/5bb7d7b0a3a449e5b1ebacf5a242b4cbb118de58/Cecret.nf#L1209-L1301

**Comment by friesac** [comment]
Agreed, I would however continue to create the IVAR_CONSENSUS directory with the independent consensus fasta for each specimen in that directory.
